version: '3.8'

volumes:
    mongo_data:
    supergraph_data:


services:
    mongo-express:
        image: mongo-express:latest
        ports:
            - 8081:8081
        depends_on:
            - mongo
        env_file:
            - ./.env
        restart: always

    auth:
        build: ./auth-dev
        env_file:
            - ./.env
        volumes:
            - ./auth-dev:/app

    web:
        build: 
            context: ./web
            dockerfile: dev.Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./web:/web
