version: '3.8'

volumes:
    supergraph_data:


services:
    composer:
        build: ./composer
        volumes:
            - supergraph_data:/data

    gateway:
        build: ./gateway
        volumes:
            - supergraph_data:/data
        env_file:
            - ./.env
        depends_on:
            composer:
                condition: service_completed_successfully

    mongo:
        image: mongo:6.0.2
        volumes:
            - ./.mounted/mongo:/data/db
        env_file:
            - ./.env
        restart: always

    files:
        build: ./files
        volumes:
            - ./.mounted/files:/files
        env_file:
            - ./.env

    nginx:
        image: nginx:1.23-alpine
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - auth
            - files
            - gateway
            - web

    auth:
        build: ./auth
        env_file:
            - ./.env

    web:
        build: ./web
        env_file:
            - ./.env

    users:
        build: ./users
        env_file:
            - ./.env
        depends_on:
            - mongo

    interfaces:
        build: ./interfaces
        env_file:
            - ./.env
        depends_on:
            - mongo

    events:
        build: ./events
        env_file:
            - ./.env
        depends_on:
            - mongo

    clubs:
        build: ./clubs
        env_file:
            - ./.env
        depends_on:
            - mongo
    
    # discussion:
    #   build: ./discussion
    #   env_file:
    #     - ./.env
    #   depends_on:
    #     - mongo
