version: '3.8'

volumes:
    mongo_data:
    supergraph_data:


services:
    composer:
        build: ./composer
        volumes:
            - supergraph_data:/data

    gateway:
        build: ./gateway
        volumes:
            - supergraph_data:/data
        env_file:
            - ./.env
        depends_on:
            composer:
                condition: service_completed_successfully

    mongo:
        image: mongo:6.0.2
        volumes:
            - mongo_data:/data/db
        env_file:
            - ./.env
        restart: always

    mongo-express:
        image: mongo-express:latest
        ports:
            - 8081:8081
        depends_on:
            - mongo
        env_file:
            - ./.env
        restart: always

    files:
        build: ./files
        env_file:
            - ./.env

    nginx:
        image: nginx:1.23-alpine
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - auth
            - files
            - gateway
            - web

    auth:
        build: ./auth-dev
        env_file:
            - ./.env
        volumes:
            - ./auth-dev:/app

    web:
        build: ./web
        env_file:
            - ./.env

    users:
        build: ./users
        env_file:
            - ./.env
        depends_on:
            - mongo
        volumes:
            - ./users:/app

    interfaces:
        build: ./interfaces
        env_file:
            - ./.env
        depends_on:
            - mongo
        volumes:
            - ./interfaces:/app

    events:
        build: ./events
        env_file:
            - ./.env
        depends_on:
            - mongo
        volumes:
            - ./events:/app

    clubs:
        build: ./clubs
        env_file:
            - ./.env
        depends_on:
            - mongo
        volumes:
            - ./clubs:/app
    
    # discussion:
    #   build: ./discussion
    #   env_file:
    #     - ./.env
    #   depends_on:
    #     - mongo
