version: "3.8"

volumes:
  subgraphs_data:

networks:
  reverse_proxy:
    external: true

services:
  mongo:
    image: mongo:4.4.18
    volumes:
      - /mnt/share/mongo_stage:/data/db
    env_file:
      - ./.env

  gateway:
    image: cc-gateway:latest
    volumes:
      - subgraphs_data:/subgraphs
    env_file:
      - ./.env
      - ./gateway/.env
    depends_on:
      - interfaces
      - clubs
      - events
      - users

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    expose:
      - 80
    depends_on:
      - auth
      - files
      - gateway
      - web
    environment:
      - VIRTUAL_HOST=dev.clubs.iiit.ac.in
      # - LETSENCRYPT_HOST=clubs.iiit.ac.in
    networks:
      - default
      - reverse_proxy

  feeder:
    image: cc-feeder:latest
    volumes:
      - ./data:/data
    depends_on:
      - mongo
    env_file:
      - ./.env

  web:
    image: cc-web:latest

  auth:
    image: cc-auth:latest
    env_file:
      - ./.env
      - ./auth/.env

  files:
    image: cc-files:latest
    volumes:
      - /mnt/share/files1:/files
    env_file:
      - ./.env
      - ./files/.env

  # subgraphs
  interfaces:
    image: cc-interfaces:latest
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env
      - ./interfaces/.env

  clubs:
    image: cc-clubs:latest
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env

  events:
    image: cc-events:latest
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env

  users:
    image: cc-users:latest
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env
