version: '3.8'

volumes:
  mongo_data:
  supergraph_data:


services:
  mongo:
    image: mongo:6.0.2
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./.env
    restart: always

  composer:
    build: ./composer
    volumes:
      - supergraph_data:/data
        
  gateway:
    build: ./gateway
    ports: 
      - 8000:8000
    volumes:
      - supergraph_data:/data
    depends_on:
      composer:
        condition: service_completed_successfully

  # auth:
  #   build: ./auth
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mongo

  # events:
  #   build: ./events
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mongo

  clubs:
    build: ./clubs
    env_file:
      - ./.env
    depends_on:
      - mongo

  # discussion:
  #   build: ./discussion
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mongo

  # mailing:
  #   build: ./mailing
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mongo
