version: "3.8"

volumes:
  subgraphs_data:

services:
  mongo:
    image: mongo:4.4.18
    volumes:
      - ./.mounted/mongo:/data/db
    env_file:
      - ./.env
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - ./.env

  gateway:
    build: ./gateway
    volumes:
      - subgraphs_data:/subgraphs
    env_file:
      - ./.env
      - ./gateway/.env
    depends_on:
      - interfaces
      - clubs
      - events
      - users

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static_files:/usr/share/nginx/others
    ports:
      - 80:80
    depends_on:
      - auth
      - files
      - gateway
      - web

  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
      args:
        - ENV=development
    volumes:
      - ./web:/web
    env_file:
      - ./web/.env

  # apis
  auth:
    build: ./apis/auth-dev
    volumes:
      - ./apis/auth-dev:/app
    env_file:
      - ./.env
      - ./apis/auth-dev/.env

  files:
    build: ./apis/files
    volumes:
      - ./.mounted/files:/files
    env_file:
      - ./.env
      - ./apis/files/.env

  # subgraphs
  interfaces:
    build: ./subgraphs/interfaces
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env
      - ./subgraphs/interfaces/.env

  clubs:
    build: ./subgraphs/clubs
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env

  events:
    build: ./subgraphs/events
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env

  users:
    build: ./subgraphs/users
    volumes:
      - subgraphs_data:/subgraphs
    depends_on:
      - mongo
    env_file:
      - ./.env
    dns:
      - 10.4.20.204
